### PR TITLE
Issue #9 - Entity PersonRole

### LINKED ISSUE #9: Issue #9 - Entity PersonRole
### Description

In the _Lvivelectrotrans_ company, each employee is assigned to some specific role, that correspond to his/her skills. In addition, the company often engages external experts who provide their services to the company on a temporary or permanent basis. Several employees may have the same role.

Therefore, it is necessary to create the `PersonRole` entity with the following properties:

- [x] `name: String`; required.
- [x] `desc: String`; nonrequired.

Also, the `Person` entity must have one additional property:

- [x] `PersonRole: PersonRole`; required.

UI changes:

- [x] Create Part Centre and Master for `PersonRole` with all the necessary properties.

### Expected outcome

It is possible to find the information about the role of the selected employee and select all employees who match the given role.

### PR DESCRIPTION
**Pull request by Sukhorskyy**
Resolve #9

### CODE REVIEW

**Review by elem3ntary — COMMENTED** [review]
Well done! No comments or suggestion here. From my understanding this Issue has merged branch from #7. Waiting for your response to comments over there.

**Comment by Tsalyk** [comment]
Great implementation!

**Review by Tsalyk — COMMENTED** [review]
Great implementation!

**Comment by Severyn12** [comment]
Good job, don't have any comments and remarks, merge to develop!

**Review by Severyn12 — COMMENTED** [review]
Good job, don't have any comments and remarks, merge to develop!

**Pull request merged**
