### PR TITLE
tst

### PR DESCRIPTION
**Pull request by Tsalyk**
Resolve Issue #3.

### CODE REVIEW

**Comment by marko7bub** [comment]
Great job! Very important entity, glad to see it implemented so well.

**Comment by Sukhorskyy** [comment]
It seems that there is a conflict here. Try to solve it via command line.

**Comment by Severyn12** [comment]
Nice work, but before merging resolve some conflicts.

**Review by Severyn12 — COMMENTED** [review]
Nice work, but before merging resolve some conflicts.

**Review by Sukhorskyy — COMMENTED** [review]
Found some useful information about resolving conflicts: [Link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line#further-reading)

**Pull request closed without merging**
