### PR TITLE
Issue #5 - Entity Vehicle

### LINKED ISSUE #5: Issue #5 - Entity Vehicle
### Description
Should implement a new entity `Vehicle`, that will represent the specific vehicle and will carry all necessary information about it.

This class will have several properties:
- [x] Property `licensePlate`: `String`; required,  as a part of the unique key identifier.
- [x] Property `model`: `String`; required.
- [x] Property `desc`: `String`; required.
- [x] Property `currentLocation`: `String`; required.
- [x] Property `active`: `Boolean`; required.
- [x] Property `driver`: `Person`; required.

UI changes: 

- [x] Modify UI to include `Vehicle` class with its new properties.
- [x] Create `Vehicle` class centre and master

### Expected outcome

Created a new Vehicle record, that possesses information about its unique license plate, model name, current location, fuel level, driver, and workable status.

### PR DESCRIPTION
**Pull request by Severyn12**
Resolved Issue #5 (about the Vehicle entity).

### CODE REVIEW

**Comment by Tsalyk** [comment]
Resolve conflicts please!

**Comment by Sukhorskyy** [comment]
There seems to be a bit of a conflict. It is probably worth to try to solve it manually.

**Comment by Severyn12** [comment]
Okay, at the moment all conflicts are resolved, take a look.

**Comment by Sukhorskyy** [comment]
Well done! Thank You!

**Comment by marko7bub** [comment]
Everything looks good now!

**Pull request merged**
